plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.cosio'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'com.pgvector:pgvector:0.1.6'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'com.bucket4j:bucket4j_jdk17-core:8.19.0'
	// testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	runtimeOnly 'org.postgresql:postgresql'

	implementation 'org.hibernate.orm:hibernate-vector:7.4.1.Final'
	implementation 'org.springframework.security:spring-security-crypto:6.5.1'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	implementation 'io.jsonwebtoken:jjwt-impl:0.12.6'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.12.6'

	implementation 'org.springframework.boot:spring-boot-starter-mail'
}

tasks.named('test') {
	useJUnitPlatform()
	testLogging() {
		events "passed", "skipped", "failed", "standardOut"
	}
}
