spring:
  application:
    name: lm
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${SMTP_PASSWORD} #"drmubgbarnqjqmwg"
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
    

  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot_db
    username: ${DB_USER}
    # password: your_password
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  
# move to an env variable before deploying
jwt:
  secret:  ${JWT_KEY} #JbjvLyK2xnoudn6Z4X0rLhl4Yuxi9bOPdd6B55yvF68=
